Repository knqyf263/pet, pull requests merged in 2024-02, with the labels that each got.

#241 Fix execution of command with quotes on windows.
  cmd/util.go
  cmd/util_unix.go
  cmd/util_windows.go
Labels: bug

#257 fix: :bug: Updated insert params to match new search format
  dialog/params.go
  dialog/params_test.go
Labels: bug

#260 feat: :sparkles: Added order to parameters based on order of occurrence
  dialog/params.go
  dialog/params_test.go
  dialog/view.go
Labels: enhancement

#142 supporting a ShowCommand option which does exactly the same as --command
  cmd/exec.go
Labels: feature-request

#256 new: tempfile-handling
  cmd/new.go
Labels: enhancement

#259 Parameters width and position modification
  dialog/view.go
Labels: enhancement
